const DUPLICATE_EMAIL = `DUPLICATE_EMAIL`;
const ERR_USER_NOT_FOUND = `USER_NOT_FOUND`;
const ERR_USER_OR_PASSWORD_NOT_FOUND = `USER_OR_PASSWORD_NOT_FOUND`;
const ERR_INVALID_PASSWORD = `INVALID_PASSWORD`;
const ERR_INVALID_TOKEN = `TOKEN_ERROR`;

export {
  DUPLICATE_EMAIL,
  ERR_USER_NOT_FOUND,
  ERR_INVALID_PASSWORD,
  ERR_USER_OR_PASSWORD_NOT_FOUND,
  ERR_INVALID_TOKEN,
};
